### PR TITLE
Update readme with bs-typing

### PR DESCRIPTION
**Pull request by arecvlohe**

### CODE REVIEW

**Comment by bordoley** [comment]
eh, i wouldn’t recommend adding rx-reason right now. 1) given my initial target was bucklescript, and the fact that i couldn’t match rxjs performance, i abandoned working on the library for the time being, 2) there is no proper release of the library. 3) a future native only version will likely have a reworked api.

**Comment by arecvlohe** [comment]
Considering there is not a comparable library, it might be a good starting place for others. I was looking for something similar for a while and just now stumbled upon it.

I am curious, why do you think you weren't able to match rxjs performance? Is that the main hindrance?

**Comment by arecvlohe** [comment]
If @bordoley is adamant about not including rx-reason, then I will remove it and  I will keep `bs-typing`.

**Comment by bordoley** [comment]
Limitations in bucklescript are mostly at fault. Function currying in callbacks for instance is a huge source of performance degradation for high throughput  rx streams. Also bucklescript compiling records as arrays is less performant than using js objects or classes. Metapoint is that bucklescript is excellent for implementing application logic, but performance sensitive code should be implemented natively.

**Comment by bordoley** [comment]
My objection is that I’m not maintaining rx-reason currently, and I dont want to encourage adoption of an incomplete and less performant library for the bucklescript use case, when writing rxjs bindings is trivial.

**Comment by vramana** [comment]
@arecvlohe Thanks!!

**Pull request merged**
