### PR TITLE
Add encode and decode JSON libraries

### PR DESCRIPTION
**Pull request by nhducit**

### CODE REVIEW

**Comment by chenglou** [comment]
Hummm... this is another area we need to clean up. There are simply too many ways to do JSON

**Comment by jihchi** [comment]
Another encode/decode JSON library: https://github.com/mlms13/bs-decode

**Comment by nhducit** [comment]
> Hummm... this is another area we need to clean up. There are simply too many ways to do JSON

It is exciting to hear this news. bs-json + gentype is quite big. 

base (without bs-json) vs bs-json
image

**Comment by vramana** [comment]
Thanks!!

**Comment by vramana** [comment]
@jihchi Can you submit a PR?

**Comment by nhducit** [comment]
> > Hummm... this is another area we need to clean up. There are simply too many ways to do JSON
> 
> It is exciting to hear this news. bs-json + gentype is quite big.
> 
> base (without bs-json) vs bs-json
> image

oh, in the above picture I compiled to `commonjs` instead of `es6`. after change to `es6` the bundle size drop a lot
Screenshot 2020-02-06 at 1 03 09 PM

**Comment by jihchi** [comment]
> @jihchi Can you submit a PR?

Sure, here you are #94

**Pull request merged**
